##########################################################################
# NSAp - Copyright (C) CEA, 2021 - 2025
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

"""
Quality assurance workflow.
"""

import shutil

import brainprep.interfaces as interfaces

from ..decorators import (
    BidsHook,
    CoerceparamsHook,
    LogRuntimeHook,
    SaveRuntimeHook,
    SignatureHook,
    step,
)
from ..typing import (
    Directory,
    File,
)
from ..utils import (
    Bunch,
    print_info,
)


@step(
    hooks=[
        CoerceparamsHook(),
        BidsHook(
            process="quality_assurance",
            bids_file="image_files",
            container="neurospin/brainprep-quality_assurance",
        ),
        LogRuntimeHook(
            title="Subject Level Quality Assurance",
            clear=True,
        ),
        SaveRuntimeHook(),
        SignatureHook(),
    ]
)
def brainprep_quality_assurance(
        image_files: list[File],
        output_dir: Directory,
        keep_intermediate: bool = False,
        **kwargs: dict,
    ) -> Bunch:
    """
    Subject level quality assurance pre-processing workflow for MRI images.

    Applies MRIQC tool :footcite:p:`esteban2017mriqc` with subject level
    default settings.

    Parameters
    ----------
    image_files : list[File]
        Path to the input image files of one subject.
    output_dir : Directory
        Directory where the quality assurance related outputs will be saved
        (i.e., the root of your dataset).
    keep_intermediate : bool
        If True, retains intermediate results (i.e., the workspace); useful
        for debugging.
        Default False.
    **kwargs : dict
        entities: list[dict]
            Dictionaries of parsed BIDS entities.


    Returns
    -------
    Bunch
        A dictionary-like object containing:

        - iqm_files : list[File] — paths to the subject level Image Quality
          Metrics (IQMs).

    Notes
    -----
    This workflow assumes the input images are organized in BIDS.

    References
    ----------

    .. footbibliography::

    Examples
    --------
    >>> from brainprep.config import Config
    >>> from brainprep.reporting import RSTReport
    >>> from brainprep.workflow import brainprep_quality_assurance
    >>>
    >>> with Config(dryrun=True, verbose=False):
    ...     report = RSTReport()
    ...     outputs = brainprep_quality_assurance(
    ...         image_files=[
    ...             "/tmp/dataset/rawdata/sub-01/ses-01/anat/"
    ...             "sub-01_ses-01_run-01_T1w.nii.gz",
    ...             "/tmp/dataset/rawdata/sub-01/ses-01/dwi/"
    ...             "sub-01_ses-01_run-01_dwi.nii.gz",
    ...         ],
    ...         output_dir="/tmp/dataset/derivatives",
    ...     )
    >>> outputs
    Bunch(
        iqm_files: [PosixPath('...'), PosixPath('...')]
    )
    """
    workspace_dir = output_dir / "workspace"
    workspace_dir.mkdir(parents=True, exist_ok=True)
    print_info(f"setting workspace directory: {workspace_dir}")

    iqm_files = interfaces.subject_level_qa(
        image_files,
        workspace_dir,
        output_dir,
    )

    if not keep_intermediate:
        print_info(f"cleaning workspace directory: {workspace_dir}")
        shutil.rmtree(workspace_dir)

    return Bunch(
        iqm_files=iqm_files,
    )


@step(
    hooks=[
        CoerceparamsHook(),
        BidsHook(
            process="quality_assurance",
            container="neurospin/brainprep-quality_assurance",
        ),
        LogRuntimeHook(
            title="Group Level Quality Assurance",
            clear=True,
        ),
        SaveRuntimeHook(),
        SignatureHook(),
    ]
)
def brainprep_group_quality_assurance(
        modalities: list[str],
        output_dir: Directory,
        keep_intermediate: bool = False,
    ) -> Bunch:
    """
    Group-level quality assurance pre-processing.

    Summarizes the generated metrics :footcite:p:`esteban2017mriqc` and
    applies the following quality control:

    1) Generate TSV tables of Image Quality Metrics (IQMs) generated by MRIQC.
    2) Generate TSV tables of filtered IQMs.
    3) TODO: Apply threshold-based quality checks on the selected quality
       metrics.
    4) TODO: Generate a histogram showing the distribution of these quality
       metrics.

    For a detailed procedure on how we filter IQMs refer :ref:`this tutorial
    <sphx_glr_auto_examples_tutorials_plot_iqms.py>`

    Parameters
    ----------
    modalities: list[str]
        The modalities in the current study.
    output_dir : Directory
        Directory where the quality assurance related outputs will be saved
        (i.e., the root of your dataset).
    keep_intermediate : bool
        If True, retains intermediate results (no effect on this workflow).
         Default False.

    Returns
    -------
    Bunch
        A dictionary-like object containing:

        - iqm_files : list[File] — paths to the selected set o group-level
          uncorrelated Image Quality Metrics (IQMs).

    Notes
    -----
    This workflow assumes the subject-level analyses have already been
    performed.

    References
    ----------

    .. footbibliography::

    Examples
    --------
    >>> from brainprep.config import Config
    >>> from brainprep.reporting import RSTReport
    >>> from brainprep.workflow import brainprep_group_quality_assurance
    >>>
    >>> with Config(dryrun=True, verbose=False):
    ...     report = RSTReport()
    ...     outputs = brainprep_group_quality_assurance(
    ...         modalities=["T1w"],
    ...         output_dir="/tmp/dataset/derivatives",
    ...     )
    >>> outputs
    Bunch(
        iqm_files: [PosixPath('...')]
    )
    """
    iqm_files = interfaces.group_level_qa(
        modalities,
        output_dir,
    )

    iqm_metrics = interfaces.mriqc_metrics(
        iqm_files,
        output_dir,
    )

    return Bunch(
        iqm_files=iqm_metrics,
    )
