##########################################################################
# NSAp - Copyright (C) CEA, 2021 - 2025
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################


"""
MRIQC functions.
"""

from pathlib import Path

from ..decorators import (
    CoerceparamsHook,
    CommandLineWrapperHook,
    LogRuntimeHook,
    OutputdirHook,
    SignatureHook,
    step,
)
from ..typing import (
    Directory,
    File,
)


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(),
        LogRuntimeHook(
            bunched=False
        ),
        CommandLineWrapperHook(),
        SignatureHook(),
    ]
)
def subject_level_qa(
        image_files: list[File],
        workspace_dir: Directory,
        output_dir: Directory,
    ) -> tuple[list[str], tuple[File | list[File]]]:
    """
    Compute subject level Image Quality Metrics (IQMs) generated by MRIQC.

    Parameters
    ----------
    image_files : list[File]
        Path to the input image files.
    workspace_dir : Directory
        The workspace of the current processing.
    output_dir : Directory
        Directory where the IQMs will be saved.

    Returns
    -------
    command : list[str]
        Cross sectional quality analysis command-line.
    outputs : tuple[File | list[File]]
        - iqm_files : list[File] - IQM files.
    """
    rawdata_dir = image_files[0].parent.parent.parent.parent
    subject = output_dir.parent.name.replace("sub-", "")
    output_dir = output_dir.parent.parent

    iqm_files = [
        path.parent / f"{path.name.split('.')[0]}.json"
        for path in image_files
    ]
    iqm_files = [
        Path(
            str(path).replace(
                str(rawdata_dir),
                str(output_dir)
            )
        )
        for path in iqm_files
    ]

    command = [
        "mriqc",
        str(rawdata_dir),
        str(output_dir),
        "participant",
        "-w", str(workspace_dir),
        "--no-sub",
        "--no-datalad-get",
        "--notrack",
        "--participant-label", subject,
    ]

    return command, (iqm_files, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(),
        LogRuntimeHook(
            bunched=False
        ),
        CommandLineWrapperHook(),
        SignatureHook(),
    ]
)
def group_level_qa(
        modalities: list[str],
        output_dir: Directory,
    ) -> tuple[list[str], tuple[File | list[File]]]:
    """
    Compute group level Image Quality Metrics (IQMs) generated by MRIQC.

    Parameters
    ----------
    modalities: list[str]
        The modalities in the current study.
    output_dir : Directory
        Directory where the IQMs will be saved.

    Returns
    -------
    command : list[str]
        Group quality analysis command-line.
    outputs : tuple[File | list[File]]
        - iqm_files : list[File] - Group IQM files.
    """
    rawdata_dir = output_dir.parent.parent / "rawdata"

    iqm_files = [
        output_dir / f"group_{mod}.tsv"
        for mod in modalities
    ]

    command = [
        "mriqc",
        str(rawdata_dir),
        str(output_dir),
        "group",
        "--no-sub",
        "--no-datalad-get",
        "--notrack",
    ]

    return command, (iqm_files, )
