##########################################################################
# NSAp - Copyright (C) CEA, 2021 - 2025
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

""" Quality check functions.
"""

import glob
from pathlib import Path

import nibabel
import numpy as np
import pandas as pd
from scipy.stats import (
    entropy,
    pearsonr,
)
from sklearn.decomposition import IncrementalPCA

from ..decorators import (
    CoerceparamsHook,
    LogRuntimeHook,
    OutputdirHook,
    PythonWrapperHook,
    SignatureHook,
    step,
)
from ..typing import (
    Directory,
    File,
)
from ..utils import (
    coerce_to_path,
    parse_bids_keys,
    print_warn,
)


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def network_entropy(
        network_files_regex: str,
        output_dir: Directory,
        entropy_threshold: float = 12,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    Comput enetwork entropy - "structure vs randomness" metric.

    A commonly used metric to assess whether a connectivity matrix exhibits
    meaningful structure is the matrix entropy. Low entropy indicates a
    highly structured matrix, whereas high entropy suggests a random-like
    or unstructured pattern.

    Parameters
    ----------
    network_files_regex : str
        A regular expression matching TSV files generated by
        ``fmri_connectivity``. These files must contain regions
        as index and columns with connectivity values.
    output_dir : Directory
        Directory where a TSV file containing the mean correlation values is
        created.
    entropy_threshold : float
        Quality control threshold applied on the entropy score.
        Default 12.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    entropy_file : File
        A TSV file containing the network entropy for each subject/session/run.
        The table includes the columns ``participant_id``, ``session``,
        ``run``, and ``entropy``, as well as a binary ``qc`` column
        indicating the quality control result.

    Notes
    -----
    A ``qc`` column is added to the output table. It contains a binary flag
    indicating whether the entropy score do not exceeds the threshold:
    ``qc = 1`` if ``entropy < entropy_threshold``, otherwise ``qc = 0``.
    """
    entropy_file = output_dir / "network_entropy.tsv"

    if dryrun:
        return (entropy_file, )

    network_files = coerce_to_path(
        glob.glob(str(network_files_regex)),
        expected_type=list[File],
    )

    scores = pd.DataFrame(
        columns=(
            "participant_id",
            "session",
            "run",
            "entropy",
        )
    )
    for path in network_files:
        entities = parse_bids_keys(path)
        df = pd.read_csv(path, sep="\t", index_col=0)

        data = np.abs(df.values).flatten()
        data /= data.sum()
        network_entropy = entropy(data)

        scores.loc[len(scores)] = [
            entities["sub"],
            entities["ses"],
            entities["run"],
            network_entropy,
        ]

    scores["qc"] = (
        scores["entropy"] < entropy_threshold
    ).astype(int)

    scores = scores.sort_values(by=["participant_id", "session", "run"])
    scores.to_csv(
        entropy_file,
        index=False,
        sep="\t",
    )

    return (entropy_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def maskoverlap(
        maskdiff_files_regex: str,
        output_dir: Directory,
        overlap_threshold: float = 0.05,
        suffix: str | None = None,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    Compute overlap ratios between mask pairs from `maskdiff` summary files.

    This function loads TSV files produced by the ``maskdiff`` tool, extracts
    voxel counts for mask 2 and masks intersection, and computes the overlap
    ratio defined as:

        overlap = intersection_size / mask2_size

    Parameters
    ----------
    maskdiff_files_regex : str
        A regular expression matching TSV files generated by ``maskdiff``.
        These files must contain voxel counts and physical volumes (mm³) for
        each mask and their intersection.
    output_dir : Directory
        Directory where a TSV file containing the mean correlation values is
        created.
    overlap_threshold : float
        Quality control threshold applied on the overalp score.
        Default 0.05.
    suffix : str | None
        Suffix added to the generated TSV file.
        Default None.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    overlap_file : File
        A TSV file containing the overlap ratio between the intersection and
        the second mask for each subject/session/run. The table includes
        the columns ``participant_id``, ``session``, ``run``, and
        ``mask_size``, ``intersection_size``, ``overlap``, as well as a
        binary ``qc`` column indicating the quality control result.

    Notes
    -----
    A ``qc`` column is added to the output table. It contains a binary flag
    indicating whether the overlap score do not exceeds the threshold:
    ``qc = 1`` if ``overlap < overlap_threshold``, otherwise ``qc = 0``.
    """
    overlap_file = output_dir / f"mask_overlap{suffix or ''}.tsv"

    if dryrun:
        return (overlap_file, )

    score_files = coerce_to_path(
        glob.glob(str(maskdiff_files_regex)),
        expected_type=list[File],
    )

    scores = pd.DataFrame(
        columns=(
            "participant_id",
            "session",
            "run",
            "mask_size",
            "intersection_size",
            "overlap",
        )
    )
    for path in score_files:
        entities = parse_bids_keys(path)
        df = pd.read_csv(path, sep="\t")

        mask_size = df.loc[df["mask"] == "intersection", "voxels"].iloc[0]
        intersection_size = df.loc[df["mask"] == "mask2", "voxels"].iloc[0]
        overlap = mask_size / intersection_size

        scores.loc[len(scores)] = [
            entities["sub"],
            entities["ses"],
            entities["run"],
            mask_size,
            intersection_size,
            overlap,
        ]

    scores["qc"] = (
        scores["overlap"] < overlap_threshold
    ).astype(int)

    scores = scores.sort_values(by=["participant_id", "session", "run"])
    scores.to_csv(
        overlap_file,
        index=False,
        sep="\t",
    )

    return (overlap_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def meancorr(
        data_files_regex: str,
        atlas_file: File | None,
        output_dir: Directory,
        correlation_threshold: float | None = 0.5,
        suffix: str | None = None,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    Compute the mean Pearson correlation between a reference image and a list
    of input images.

    It can use pre-computed correlation data for each subject or compute the
    correlation internally.
    If the correlaton is computed internally, individual pre-computed
    correlation data are saved in the ``subjects`` directory.
    Additionally, it performs quality control based on a specified correlation
    threshold.

    Parameters
    ----------
    data_files_regex : str
        A REGEX to image files, each representing an image of the same shape
        and geometry as `atlas_file` or pre-computed TSV correlation data.
    atlas_file : File | None
        A file representing the reference image. If None, expect pre-computed
        correlation data.
    output_dir : Directory
        Directory where a TSV file containing the mean correlation values is
        created.
    correlation_threshold : float | None
        Quality control threshold on the correlation score.
        If None do not add the ``qc`` column.
        Default 0.5.
    suffix : str | None
        Suffix added to the generated TSV file.
        Default None.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    correlations_file : File
        A TSV file containing the Pearson correlation coefficient between the
        atlas image and each image pointed by the input REGEX. The table
        includes the columns ``participant_id``, ``session``, ``run``, and
        ``mean_correlation``, as well as a binary ``qc`` column indicating
        the quality control result.

    Raises
    ------
    ValueError
        If the atlas and an image have incompatible shape or geometry.
        If invalid pre-computed correlation data are provided.

    Notes
    -----
    A ``qc`` column is added to the output table. It contains a binary flag
    indicating whether the mean correlation score exceeds the threshold:
    ``qc = 1`` if ``mean_correlation > correlation_threshold``,
    otherwise ``qc = 0``.
    """
    correlations_file = output_dir / f"mean_correlations{suffix or ''}.tsv"

    if dryrun:
        return (correlations_file, )

    image_files = coerce_to_path(
        glob.glob(str(data_files_regex)),
        expected_type=list[File],
    )
    if atlas_file is not None:
        atlas_im = nibabel.load(atlas_file)
        atlas_arr = atlas_im.get_fdata()

    scores = pd.DataFrame(
        columns=(
            "participant_id",
            "session",
            "run",
            "mean_correlation",
        )
    )
    for path in image_files:
        entities = parse_bids_keys(path)
        if atlas_file is not None:
            im = nibabel.load(path)
            arr = atlas_im.get_fdata()
            if atlas_arr.shape != arr.shape:
                raise ValueError(
                    f"Atlas and image have incompatible shape: {path}"
                )
            if not np.allclose(atlas_im.affine, im.affine):
                raise ValueError(
                    f"Atlas and image have incompatible orientation: {path}"
                )
            corr, _ = pearsonr(
                atlas_arr.flatten(),
                arr.flatten(),
            )
        else:
            df_ = pd.read_csv(path, sep="\t")
            if len(df_) != 1:
                raise ValueError(
                    f"Invalid pre-computed correlation data: {path}"
                )
            corr = df_.iloc[0]["mean_correlation"]
        scores.loc[len(scores)] = [
            entities["sub"],
            entities["ses"],
            entities["run"],
            float(corr),
        ]
        if atlas_file is not None:
            individual_score = scores.iloc[[-1]]
            basename = "sub-{sub}_ses-{ses}_run-{run}_mod-{mod}".format(
                **entities
            )
            individual_score_file = (
                path.parent /
                "quality_check" /
                f"{basename}_corr.tsv"
            )
            individual_score_file.parent.mkdir(parents=True, exist_ok=True)
            individual_score.to_csv(
                individual_score_file,
                sep="\t",
                index=False,
            )

    if correlation_threshold is not None:
        scores["qc"] = (
            scores["mean_correlation"] > correlation_threshold
        ).astype(int)
    scores = scores.sort_values(by=["participant_id", "session", "run"])
    scores.to_csv(
        correlations_file,
        index=False,
        sep="\t",
    )

    return (correlations_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def maskdiff(
        mask1_file: File,
        mask2_file: File,
        output_dir: Directory,
        entities: dict,
        inv_mask1: bool = False,
        inv_mask2: bool = False,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    Compute summary statistics comparing two binary masks.

    This function loads two binary mask images, verifies that they share
    the same spatial dimensions and affine transformation, computes their
    voxel-wise intersection, and writes a summary table containing voxel
    counts and physical volumes (in mm³) for each mask and their intersection.

    Parameters
    ----------
    mask1_file : File
        Path to the first binary mask image.
    mask2_file : File
        Path to the second binary mask image.
    output_dir : Directory
        Directory where the defacing mask will be saved.
    entities : dict
        A dictionary of parsed BIDS entities including modality.
    inv_mask1 : bool
        If True, the first mask is inverted before comparison. This is
        useful when the mask represents an exclusion region rather than an
        inclusion region.
        Default False.
    inv_mask2 : bool
        If True, the second mask is inverted before comparison. This is
        useful when the mask represents an exclusion region rather than an
        inclusion region.
        Default False.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    summary_file : File
        Path to the generated summary TSV file.

    Raises
    ------
    ValueError
        If both masks have not identical shapes and affines.
    """
    basename = "sub-{sub}_ses-{ses}_run-{run}_mod-{mod}_maskdiff".format(
        **entities)
    summary_file = output_dir / f"{basename}.tsv"

    if not dryrun:

        mask1_im = nibabel.load(mask1_file)
        mask2_im = nibabel.load(mask2_file)
        mask1 = mask1_im.get_fdata().astype(bool)
        mask2 = mask2_im.get_fdata().astype(bool)

        if inv_mask1:
            mask1 = ~mask1
        if inv_mask2:
            mask1 = ~mask2

        if mask1.shape != mask2.shape:
            raise ValueError(
                f"Mask shapes differ: {mask1.shape} vs {mask2.shape}. "
                "Resampling is required."
            )
        if not np.allclose(mask1_im.affine, mask2_im.affine):
            raise ValueError(
                "Mask affines differ. Resampling is required before "
                "intersection."
            )

        intersection = np.logical_and(mask1, mask2)
        voxel_volume = np.abs(np.linalg.det(mask1_im.affine[:3, :3]))

        summary_df = pd.DataFrame({
            "mask": ["mask1", "mask2", "intersection"],
            "voxels": [
                mask1.sum(),
                mask2.sum(),
                intersection.sum(),
            ],
            "volume_mm3": [
                mask1.sum() * voxel_volume,
                mask2.sum() * voxel_volume,
                intersection.sum() * voxel_volume,
            ]
        })
        summary_df.to_csv(summary_file, sep="\t", index=False)

    return (summary_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def pca(
        image_files_regex: str,
        output_dir: Directory,
        batch_size: int = 10,
        suffix: str | None = None,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    Perform an Incremental PCA with 2 components on a collection of images
    matched by a regex pattern, processing them in batches.

    The function loads all images matching the provided regex, splits them
    into batches, and incrementally fits a PCA model using scikit-learn's
    ``IncrementalPCA``. Each image is flattened into a 1D vector before
    processing. After fitting, the function transforms all batches to obtain
    the first two principal components for each image. These components are
    saved in a TSV file as two columns named ``pc1`` and ``pc2``. BIDS
    entities (``participant_id``, ``session``, ``run``) are extracted from
    filenames using ``parse_bids_keys`` and included in the output table.

    Parameters
    ----------
    image_files_regex : str
        A REGEX to image files, each representing an image,
        all images must have the same size.
    output_dir : Directory
        Directory where a TSV file containing the values of the first two
        components created by the PCA ill be saved, a Directory containing
        all the graph of all batch.
    batch_size : int
        Number of images to use in each batch. If None, a single batch is used.
        Default 10.
    suffix : str | None
        Suffix added to the generated TSV file.
        Default None.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    pca_file : File
        Path to the generated ``pca.tsv`` file containing the PCA results.

    Raises
    ------
    ValueError
        If no image matches the regex pattern.
        If the dataset contains fewer than 2 images, which prevents PCA
        computation.
    """
    pca_file = output_dir / f"pca{suffix or ''}.tsv"

    if dryrun:
        return (pca_file, )

    image_files = glob.glob(str(image_files_regex))
    n_images = len(image_files)
    if n_images == 0:
        raise ValueError(
            f"No image matches the regex pattern: {image_files_regex}"
        )
    if n_images < 2:
        raise ValueError(
            f"The dataset contains fewer than 2 images: {n_images}"
        )
    batches = [
        image_files[idx:idx + batch_size]
        for idx in range(0, len(image_files), batch_size)
    ]

    pca = IncrementalPCA(n_components=2)
    for batch_files in batches:
        data = [
            nibabel.load(file_).get_fdata().flatten()
            for file_ in batch_files
        ]
        pca.partial_fit(data)

    df = []
    for batch_files in batches:
        data = [
            nibabel.load(file_).get_fdata().flatten()
            for file_ in batch_files
        ]
        components = pca.transform(data)
        info = [
            parse_bids_keys(Path(file_))
            for file_ in batch_files
        ]
        partial_df = pd.DataFrame({
            "participant_id": [item["sub"] for item in info],
            "session": [item["ses"] for item in info],
            "run": [item["run"] for item in info],
            "pc1": components[:, 0],
            "pc2": components[:, 1],
            "explained_variance_ratio_pc1": [
                pca.explained_variance_ratio_[0],
            ] * len(info),
            "explained_variance_ratio_pc2": [
                pca.explained_variance_ratio_[1],
            ] * len(info),
        })
        df.append(partial_df)

    df = pd.concat(df, ignore_index=True)
    df.to_csv(pca_file, index=False, sep="\t")

    return (pca_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def eulernums(
        output_dir: Directory,
        euler_threshold: int = -217,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    FreeSurfer recon-all quality control.

    Parse the FreeSurfer's Euler numbers for all subjects and applies the
    quality control described in :footcite:p:`rosen2018euler`.

    Parameters
    ----------
    output_dir : Directory
        FreeSurfer working directory containing all the subjects.
    euler_threshold : int
        Quality control threshold on the Euler number.
        Default 217.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    euler_numbers_file : File
        A TSV file containing FreeSurfer's averaged Euler numbers. The table
        includes the columns ``participant_id``, ``session``, ``run``, and
        ``euler_number``, as well as a binary ``qc`` column indicating
        the quality control result.

    Notes
    -----
    A ``qc`` column is added to the output table. It contains a binary flag
    indicating whether the euler score exceeds the threshold:
    ``qc = 1`` if ``euler_number > euler_threshold``,
    otherwise ``qc = 0``.

    References
    ----------

    .. footbibliography::
    """
    euler_numbers_file = output_dir / "euler_numbers.tsv"

    if dryrun:
        return (euler_numbers_file, )

    log_files = glob.glob(str(
        output_dir.parent /
        "subjects" /
        "sub-*" /
        "ses-*" /
        "run-*" /
        "scripts" /
        "recon-all.log"
    ))
    log_files = [
        Path(item) for item in log_files
    ]

    scores = pd.DataFrame(
        columns=(
            "participant_id",
            "session",
            "run",
            "euler_number",
        )
    )
    for path in log_files:
        entities = parse_bids_keys(path, full_path=True)
        lines = path.read_text().splitlines()
        selection = [item for item in lines
                     if item.startswith("orig.nofix lheno")]
        if len(selection) != 1:
            print_warn(f"no Euler number: {entities}")
            euler_number = float("-inf")
        else:
            (_, left_euler_number,
             right_euler_number) = selection[0].split("=")
            left_euler_number, _ = left_euler_number.split(",")
            euler_number = 0.5 * (
                 int(left_euler_number.strip()) +
                 int(right_euler_number.strip())
            )
        scores.loc[len(scores)] = [
            entities["sub"],
            entities["ses"],
            entities["run"],
            euler_number,
        ]

    scores["qc"] = (scores["euler_number"] > euler_threshold).astype(int)
    scores = scores.sort_values(by=["participant_id", "session"])
    scores.to_csv(
        euler_numbers_file,
        index=False,
        sep="\t",
    )

    return (euler_numbers_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def vbm_metrics(
        output_dir: Directory,
        ncr_threshold: float = 4.5,
        iqr_threshold: float = 4.5,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    CAT12 VBM quality control.

    The following quality metrics are considered:

    - Image Correlation Ratio (ICR) - Measures how well the subject's image
      aligns with a reference template. High ICR suggests good
      registration quality.
    - Noise to Contrast Ratio (NCR) - Assesses image clarity by comparing
      noise levels to tissue contrast. Lower NCR may indicate poor image
      quality.
    - Image Quality Rating (IQR) - A composite score summarizing overall
      scan quality. Combines multiple metrics like noise, resolution,
      and bias field. Higher IQR = better quality.

    Parse these metrics and applies the quality control described in
    :footcite:p:`dufumier2022openbhb`.

    Parameters
    ----------
    output_dir : Directory
        Working directory containing the outputs.
    ncr_threshold : float
        Quality control threshold on the NCR scores.
        Default 4.5.
    iqr_threshold : float
        Quality control threshold on the IQR scores.
        Default 4.5.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    group_stats_file : File
        A TSV file containing quality metrics. The table includes the columns
        ``participant_id``, ``session``, ``run``, and ``ICR``, ``NCR``,
        ``IQR``, as well as a binary ``qc`` column indicating the quality
        control result.

    Notes
    -----
    A ``qc`` column is added to the output table. It contains a binary flag
    indicating whether the NCR and ICR scores do not exceed input thresholds:
    ``qc = 1`` if ``NCR < ncr_threshold & ICR < icr_threshold``,
    otherwise ``qc = 0``.

    References
    ----------

    .. footbibliography::
    """
    group_stats_file = output_dir / "group_stats.tsv"

    if dryrun:
        return (group_stats_file, )

    report_files = coerce_to_path(
        glob.glob(str(
            output_dir.parent /
            "subjects" /
            "sub-*" /
            "ses-*" /
            "report" /
            "cat_*T1w.xml"
        )),
        expected_type=list[File]
    )
    entities = [
        parse_bids_keys(path)
        for path in report_files
    ]

    stats = []
    for info, path in zip(entities, report_files, strict=True):
        df = pd.read_xml(
            path,
            iterparse={"qualityratings": ["ICR", "NCR", "IQR"]},
        )
        df.insert(0, "participant_id", info["sub"])
        df.insert(1, "session", info["ses"])
        df.insert(2, "run", info["run"])
        stats.append(df)
    df = pd.concat(stats)
    df.sort_values(by=["participant_id"], inplace=True)

    df["qc"] = (
        (df["NCR"] < ncr_threshold) &
        (df["IQR"] < iqr_threshold)
    ).astype(int)

    df.to_csv(
        group_stats_file,
        index=False,
        sep="\t",
    )

    return (group_stats_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def fmriprep_metrics(
        output_dir: Directory,
        fd_mean_threshold: float = 0.2,
        dvars_std_threshold: float = 1.5,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    FMRIprep quality control.

    The following quality metrics are considered:

    - ``fd_mean`` : mean framewise displacement, a measure of head motion
      across the time series.
    - ``dvars_std`` : mean standardized DVARS, quantifying the rate of change
      in BOLD signal intensity between consecutive volumes.

    Parameters
    ----------
    output_dir : Directory
        Working directory containing the outputs.
    fd_mean_threshold : float
        Quality control threshold on the Mean Framewise Displacement (mm).
        Default 0.2.
    dvars_std_threshold : float
        Quality control threshold on the Standardized DVARS.
        Default 1.5.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    group_stats_file : File
        A TSV file containing quality metrics. The table includes the columns
        ``participant_id``, ``session``, ``run``, and ``fd_mean``,
        ``dvars_std``, as well as a binary ``qc`` column indicating the
        quality control result.

        - ``participant_id`` : subject identifier
        - ``fd_mean`` : mean framewise displacement
        - ``dvars_std`` : mean standardized DVARS
        - ``qc`` : quality check output

    Notes
    -----
    Missing metrics (e.g., ``snr`` or ``aor``) are filled with ``NaN``.
    """
    group_stats_file = output_dir / "motion_confounds.tsv"

    if dryrun:
        return (group_stats_file, )

    report_files = glob.glob(str(
        output_dir.parent / "subjects" / "sub-*" / "ses-*" / "func" /
        "*desc-confounds_timeseries.tsv"
    ))
    entities = [
        parse_bids_keys(Path(path))
        for path in report_files
    ]

    def safe_mean(df, col):
        if col not in df:
            return np.nan
        return (
            df[col]
            .replace("n/a", np.nan)
            .astype(float)
            .mean()
        )

    stats = []
    for info, path in zip(entities, report_files, strict=True):
        df = pd.read_csv(
            path,
            sep="\t",
        )
        stats.append(pd.DataFrame.from_dict(
            {
                "participant_id": [info["sub"]],
                "session": [info["ses"]],
                "run": [info["run"]],
                "fd_mean": [safe_mean(df, "framewise_displacement")],
                "dvars_std": [safe_mean(df, "std_dvars")],
            }
        ))

    df = pd.concat(stats)
    df.sort_values(by=["participant_id"], inplace=True)

    df["qc"] = (
        (df["fd_mean"] < fd_mean_threshold) &
        (df["dvars_std"] < dvars_std_threshold)
    ).astype(int)

    df.to_csv(
        group_stats_file,
        index=False,
        sep="\t",
    )

    return (group_stats_file, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def mriqc_metrics(
        iqm_files: list[File],
        output_dir: Directory,
        dryrun: bool = False,
    ) -> list[File]:
    """
    Filter MRIQC group-level metrics according to modality-specific defaults.

    Each input file must follow the naming pattern ``group_<modality>.tsv``.
    Based on the modality extracted from the filename (e.g., T1w, bold, dwi),
    a predefined set of uncorrelated Image Quality Metrics (IQMs) is selected.
    The function then writes a filtered TSV file containing only those metrics
    to the specified output directory.

    Parameters
    ----------
    iqm_files : list[File]
        Paths to MRIQC group-level metrics files.
    output_dir : Directory
        Directory where the filtered metrics will be written.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    filter_iqm_files : list[File]
        Paths to the selected set of uncorrelated group-level IQMs.

    Raises
    ------
    ValueError
        If modality extracted from the filename is unsupported
        If the filename does not follow the expected pattern
        ``group_<modality>.tsv``.
    """
    filter_iqm_files = [
        output_dir / f"filter_{path.name}"
        for path in iqm_files
    ]

    if dryrun:
        return (iqm_files, )

    selected_metrics = {
        "T1w": [
            "cjv", "cnr", "efc", "fber", "wm2max", "inu_med", "qi_1", "qi_2",
            "icvs_wm", "fwhm_avg", "rpve_wm", "snr_wm", "snrd_wm", "wm2max",
        ],
        "bold": [
            "aor", "aqi", "dummy_trs", "dvars_vstd", "efc", "fber",
            "fd_mean", "fwhm_avg", "gcor", "gsr_x", "gsr_y", "snr", "tsnr",
        ],
        "dwi": [
            "bdiffs_max", "bdiffs_median", "efc_shell01", "efc_shell02",
            "fber_shell01", "fber_shell02", "fd_mean", "ndc", "sigma_pca",
            "sigma_piesno", "snr_cc_shell0", "snr_cc_shell1_best",
            "snr_cc_shell1_worst", "spikes_global",
        ]
    }
    for input_file, output_file in zip(
            iqm_files, filter_iqm_files, strict=True,
        ):

        if not input_file.stem.startswith("group_"):
            raise ValueError(
                f"Invalid filename '{input_file.name}': expected "
                "'group_<modality>.tsv'."
            )

        df = pd.read_csv(input_file, sep="\t")

        modality = input_file.stem.replace("group_", "")
        if modality not in selected_metrics:
            raise ValueError(
                f"Unsupported modality '{modality}'. "
                f"Expected one of: {', '.join(selected_metrics)}."
            )

        df = df[["bids_name", *selected_metrics[modality]]]
        df.to_csv(output_file, sep="\t", index=False)

    return (filter_iqm_files, )


@step(
    hooks=[
        CoerceparamsHook(),
        OutputdirHook(
            quality_check=True
        ),
        LogRuntimeHook(
            bunched=False,
            parent=True
        ),
        PythonWrapperHook(),
        SignatureHook(),
    ]
)
def sulcirec_metrics(
        output_dir: Directory,
        dryrun: bool = False,
    ) -> tuple[File]:
    """
    Morphologist quality control.

    Parameters
    ----------
    output_dir : Directory
        Working directory containing the outputs.
    dryrun : bool
        If True, skip actual computation and file writing.
        Default False.

    Returns
    -------
    group_stats_file : File
        A TSV file containing  a binary ``qc`` column indicating the
        morphologist quality control result.

    References
    ----------

    .. footbibliography::
    """
    group_stats_file = output_dir / "group_stats.tsv"

    if dryrun:
        return (group_stats_file, )

    pattern = "sub-*/ses-*/run-*/qc.tsv"
    status_files = list(
        (output_dir.parent / "subjects").glob(pattern)
    )
    if len(status_files) == 0:
        print_warn(f"No data found: {pattern}")
    entities = [
        parse_bids_keys(path, full_path=True)
        for path in status_files
    ]

    stats = []
    for info, path in zip(entities, status_files, strict=True):
        df_ = pd.read_csv(path, sep="\t")
        df = pd.DataFrame({
            "participant_id": [info["sub"]],
            "session": [info["ses"]],
            "run": [info["run"]],
            "qc": [int(all(df_["morpho_qc"].values == "OK"))],
        })
        stats.append(df)
    df = pd.concat(stats)
    df.sort_values(by=["participant_id", "session", "run"], inplace=True)

    df.to_csv(
        group_stats_file,
        index=False,
        sep="\t",
    )

    return (group_stats_file, )
