[brainprep.mapping]
ALL = [
    "subject-level-qa --image-files {mod} --output-dir {outdir}",
    "group-level-qa --modalities {mod_names} --output-dir {outdir}",
]
T1w = [
    "subject-level-defacing --anatomical_file {T1w} --output-dir {outdir}",
    "group-level-defacing --modality T1w --output-dir {outdir}",
    "subject-level-quasiraw --anatomical_file {T1w} --output-dir {outdir}",
    "group-level-quasiraw --modality T1w --output-dir {outdir}",
    "subject-level-sbm --t1_file {T1w} --output-dir {outdir}",
    "longitudinal-sbm --t1_files {T1ws} --model 1 --output-dir {outdir}",
    "group-level-sbm --output-dir {outdir}",
    "subject-level-vbm --t1_file {T1w} --output-dir {outdir}",
    "longitudinal-vbm --t1_files {T1ws} --model 1 --output-dir {outdir}",
    "group-level-vbm --output-dir {outdir}",
    "subject-level-sulcirec --t1-file {T1w} --output-dir {outdir}",
    "group-level-sulcirec --output-dir {outdir}",
]
T2w = [
     "subject-level-defacing --anatomical_file {T2w} --output-dir {outdir}",
    "group-level-defacing --modality T2w --output-dir {outdir}",
    "subject-level-quasiraw --anatomical_file {T2w} --output-dir {outdir}",
    "group-level-quasiraw --modality T2w --output-dir {outdir}",
]
FLAIR = [
     "subject-level-defacing --anatomical_file {FLAIR} --output-dir {outdir}",
    "group-level-defacing --modality FLAIR --output-dir {outdir}",
    "subject-level-quasiraw --anatomical_file {FLAIR} --output-dir {outdir}",
    "group-level-quasiraw --modality FLAIR --output-dir {outdir}",
]
BOLD = [
    "subject-level-fmriprep --t1-file {T1w} --func-files {bolds} --freesurfer-dir {fsdir} --output-dir {outdir}",
    "group-level-fmriprep --output-dir {outdir}",
]
DWI = [
    "subject-level-dmriprep --t1-file {T1w} --dwi-files {dwis} --output-dir {outdir}",
]

[sbm.default]
n_cpus = 1
memory = 16
freesurfer = true

[sbm.nextflow]
memory = 64

[sbm.group]
n_cpus = 1
memory = 5
freesurfer = true

[defacing.default]
n_cpus = 1
memory = 5

[sulcirec.default]
n_cpus = 1
memory = 1

[fmriprep.default]
n_cpus = 1
memory = 10
freesurfer = true

[fmriprep.group]
n_cpus = 1
memory = 5

[quality_assurance.default]
n_cpus = 1
memory = 20

[quality_assurance.group]
n_cpus = 1
memory = 5

[quasiraw.default]
n_cpus = 1
memory = 5
freesurfer = true

[vbm.default]
n_cpus = 1
memory = 5
backend = "oneshot"

[vbm.group]
n_cpus = 1
memory = 5

[dmriprep.default]
n_cpus = 1
memory = 32
