#! /usr/bin/env python3
# -*- coding: utf-8 -*-
##########################################################################
# NSAp - Copyright (C) CEA, 2022
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

# System import
import fire
import brainprep.workflow as wf


fire.Fire({
    "fsreconall": wf.brainprep_fsreconall,
    "cat12vbm": wf.brainprep_cat12vbm,
    "quasiraw": wf.brainprep_quasiraw
})
