#! /usr/bin/env python3
# -*- coding: utf-8 -*-
##########################################################################
# NSAp - Copyright (C) CEA, 2021
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

# System import
import os
import argparse
import textwrap
from pprint import pprint
from datetime import datetime
from argparse import RawTextHelpFormatter
import brainprep


# Script documentation
DOC = """
The CAT12 VBM preprocessing script.
"""


def is_file(filearg):
    """ Type for argparse - checks that file exists but does not open.
    """
    if not os.path.isfile(filearg):
        raise argparse.ArgumentError(
            "The file '{0}' does not exist!".format(filearg))
    return filearg


def is_directory(dirarg):
    """ Type for argparse - checks that directory exists.
    """
    if not os.path.isdir(dirarg):
        raise argparse.ArgumentError(
            "The directory '{0}' does not exist!".format(dirarg))
    return dirarg


def get_cmd_line_args():
    """
    Create a command line argument parser and return a dict mapping
    <argument name> -> <argument value>.
    """
    parser = argparse.ArgumentParser(
        prog="brainprep-cat12vbm",
        description=textwrap.dedent(DOC),
        formatter_class=RawTextHelpFormatter)

    # Required arguments
    required = parser.add_argument_group("required arguments")
    required.add_argument(
        "-a", "--anatomical",
        required=True, metavar="<path>", nargs="+", type=is_file,
        help="path to the anatomical T1w Nifti file(s)."
             "Or path to anatomical T1w Nifti files of one"
             " subject if longitudinal data")
    required.add_argument(
        "-o", "--outdir",
        required=True, metavar="<path>", type=is_directory,
        help="the destination folder.")

    # Optional arguments
    parser.add_argument(
        "-L", "--longitudinal",
        action="store_true",
        help="optionally perform longitudinal cat12vbm process")
    parser.add_argument(
        "-C", "--cat12",
        metavar="<path>",
        help="path to the CAT12 standalone executable")
    parser.add_argument(
        "-S", "--spm12",
        metavar="<path>",
        help="the SPM12 folder of standalone version")
    parser.add_argument(
        "-M", "--matlab",
        metavar="<path>",
        help="Matlab Compiler Runtime (MCR) folder.")
    parser.add_argument(
        "-T", "--tpm",
        metavar="<path>",
        help="path to the SPM TPM file.")
    parser.add_argument(
        "-D", "--darteltpm",
        metavar="<path>",
        help="path to the CAT12 template file.")
    parser.add_argument(
        "-V", "--verbose",
        type=int, choices=[0, 1, 2], default=0,
        help="increase the verbosity level: 0 silent, [1, 2] verbose.")

    # Create a dict of arguments to pass to the 'main' function
    args = parser.parse_args()
    kwargs = vars(args)
    resource_dir = os.path.join(os.path.dirname(
        brainprep.__file__), "resources")
    kwargs["template_batch"] = os.path.join(
        resource_dir, "cat12vbm_matlabbatch.m")
    kwargs["template_batch_longitudinal"] = os.path.join(
        resource_dir, "cat12vbm_matlabbatch_longitudinal.m")
    if kwargs["cat12"] is None:
        kwargs["cat12"] = "/opt/spm/standalone/cat_standalone.sh"
    if kwargs["spm12"] is None:
        kwargs["spm12"] = "/opt/spm"
    if kwargs["matlab"] is None:
        kwargs["matlab"] = "/opt/mcr/v93"
    if kwargs["tpm"] is None:
        kwargs["tpm"] = (
            "/opt/spm/spm12_mcr/home/gaser/gaser/spm/spm12/tpm/TPM.nii")
    if kwargs["darteltpm"] is None:
        kwargs["darteltpm"] = (
            "/opt/spm/spm12_mcr/home/gaser/gaser/spm/spm12/toolbox/cat12/"
            "templates_volumes/Template_1_IXI555_MNI152.nii")
    verbose = kwargs.pop("verbose")

    return kwargs, verbose


"""
Parse the command line.
"""
inputs, verbose = get_cmd_line_args()
runtime = {
    "tool": "brainprep-cat12vbm",
    "timestamp": datetime.now().isoformat(),
    "tool_version": brainprep.__version__}
if verbose > 0:
    pprint("[info] Starting CAT12 VBM preprocessing...")
    pprint("[info] Runtime:")
    pprint(runtime)
    pprint("[info] Inputs:")
    pprint(inputs)


"""
Complete matlab batch.
"""
batch_file = os.path.join(inputs["outdir"], "cat12vbm_matlabbatch.m")
if inputs["longitudinal"]:
    brainprep.write_matlabbatch(
    inputs["template_batch_longitudinal"], inputs["anatomical"], inputs["tpm"],
    inputs["darteltpm"], batch_file)
else:
    brainprep.write_matlabbatch(
        inputs["template_batch"], inputs["anatomical"], inputs["tpm"],
        inputs["darteltpm"], batch_file)


"""
Launch matlab batch.
"""
cmd = [inputs["cat12"], "-s", inputs["spm12"], "-m", inputs["matlab"],
       "-b", batch_file]
brainprep.execute_command(cmd)
